[".config/alacritty/themes"]
type = "archive"
url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"


["Library/Application Support/kando/sound-themes"]
url = "https://github.com/kando-menu/sound-themes/archive/main.tar.gz"
refreshPeriod = "168h"
type = "archive"
exact = true
stripComponents = 1
include = ["*/themes/**"]


["Library/Application Support/kando/menu-themes"]
url = "https://github.com/kando-menu/menu-themes/archive/main.tar.gz"
refreshPeriod = "168h"
type = "archive"
exact = true
stripComponents = 1
include = ["*/themes/**"]
